### ISSUE TITLE
TFT to ESP32 pin connections

### ISSUE THREAD

**Issue by OK2VJZ** [aldoir/smart-linear-controller#1]
Hello,
I testing your this project, BT communication with IC-705 working ok, but I have a problem with TFT which not working, can you specify exact type of ESP32 module and pin connections between them and TFT.
VY73, Zdenek ok2vjz@email.cz

**Comment by aldoir** [comment]
Hi there, glad it's helping you somehow, please share your progress.

Did you edit the [User_Setup.h](https://github.com/aldoir/smart-linear-controller/blob/bf55958415c32345ec9ab76e0f9b1d88106b2785/lib/TFT_ILI9341/User_Setup.h#L47-L49) to match your wiring?

**Comment by aldoir** [comment]
No feedback, closing the issue
